env: dev

db:
  host: localhost
  port: 5432
  user: postgres
  password: mypass
  dbname: postgres
  sslmode: disable

  max_open_conns: 10
  max_idle_conns: 10
  conn_max_lifetime: 30m

http:
  host: 0.0.0.0
  port: 8080
  read_header_timeout: 5s
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  request_timeout: 5s

web:
  dir: ./web

log:
  level: debug
